version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 50

  - package-ecosystem: "gradle"
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "com.mojang:authlib"
      - dependency-name: "com.zaxxer:HikariCP"
      - dependency-name: "com.sk89q.worldguard:worldguard-bukkit"
      - dependency-name: "com.sk89q.worldguard:worldguard-legacy"
      - dependency-name: "org.spigotmc:spigot-api"