name: Auto Assign


on:
  pull_request_target:
    types: [ "opened", "ready_for_review" ]
  workflow_dispatch:


jobs:
  add-reviews:

    runs-on: ubuntu-22.04

    steps:
      - name: debug
        run: |
          echo "github.actor: ${{ github.actor }}"
      # https://github.com/kentaro-m/auto-assign-action
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto-assign_config.yml
