name: Build Gradle


on:
  push:
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Download BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      # https://github.com/actions/setup-java
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      # https://github.com/actions/setup-java
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build MC 1.20.6
        run: java -jar BuildTools.jar --rev 1.20.6 --remapped

      - name: Build MC 1.21
        run: java -jar BuildTools.jar --rev 1.21 --remapped

      - name: Build with Gradle
        run: ./gradlew obfuscate --no-daemon

      # https://github.com/actions/upload-artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: UltraCosmetics-dev
          path: build/libs/UltraCosmetics-*.jar
